### ISSUE TITLE
ReShade complains about high network activity

### ISSUE THREAD

**Issue by moepike** [E66666666/GTAVManualTransmission#110]
When MT is installed, Reshade Depth filters, such as RTGI, stopped working due to "high network" activity.
Check for update is disabled as well but no luck.

Please let me know if there's a way to turn off all network activity from the mod.
Thank you!

**Comment by E66666666** [comment]
Check for Update only requests a single json file (when the script initializes), so that can't be it.

The script exposes UDP telemetry at 127.0.0.1:20777, and it gets updated every frame. You can disable this by unchecking "Enable UDP Telemetry" in the Misc settings menu.

Also why the heck do ReShade depth filters get bothered by network activity?

**Comment by moepike** [comment]
That fixed it! Thank you!
Reshade says it's to prevent people from exploits and cheats. 🤷‍♂️

**Comment by celisej567** [comment]
where did you find Misc settings menu ?
