### ISSUE TITLE
Surely we shouldn't have a max gear?

### ISSUE THREAD

**Issue by SaggyBlackSack** [E66666666/GTAVManualTransmission#36]
Gears/Constants.h

**Comment by E66666666** [comment]
Commit https://github.com/E66666666/GTAVManualTransmission/commit/97d207c2788b983c30bdb574076022ee7dc414e1 moved it into `script.cpp` and commit https://github.com/E66666666/GTAVManualTransmission/commit/2fa148aaf02954e53ea0803364db8134a0d11151 moved it to `VehicleExtensions.cpp`.

It's not a constant any more since it can change depending on what game version is used.

**Comment by E66666666** [comment]
@SaggyBlackSack 
I consider this a non-issue, but feel free to re-open the issue if you have something else to add.
