### ISSUE TITLE
Other devices - e.g. Handbrake

### ISSUE THREAD

**Issue by RedDirtNurse** [E66666666/GTAVManualTransmission#8]
Is there a way to use the input from an analog handbrake?  I've got a Fanatec Clubsport - I can see the x-axis data, but I'm wondering if I can assign it also?

**Comment by E66666666** [comment]
That's what the [MultipleDevices branch](https://github.com/E66666666/GTAVManualTransmission/tree/MultipleDevices) is all about 😅 

Due to the difficulty in creating a proper config from scratch I'm currently working on a GUI tool, but I haven't had much progress.

The latest builds from this branch should fully work though, and DIUtil can be used to configure the .ini.

**Comment by RedDirtNurse** [comment]
Sorry for being such a noob:  is DIUtil an executable that I can download?  I don't have this.

**Comment by E66666666** [comment]
It's included in the latest builds on AppVeyor.

https://ci.appveyor.com/project/E66666666/gtavmanualtransmission/build/artifacts
